#Test data to verify the launch of the web application.
server.port: 8086
spring.datasource.url: jdbc:postgresql://localhost:5432/social_network
spring.datasource.username: postgres
spring.datasource.password: 80958095
spring.datasource.driver-class-name: org.postgresql.Driver
spring.liquibase.enabled: true

# Prometheus
management.endpoints.web.exposure.include: info, health, prometheus

# App Properties
skillbox.app.jwtCookieName: skill
skillbox.app.jwtSecret: skillSecretKey
skillbox.app.server: 195.133.201.227
skillbox.app.localhost: localhost
skillbox.app.server.sexy: zerone.be.sexy
skillbox.app.server.mcsoft: zerone.mcsoft.org

# Captcha
secretCaptcha: psvm

# Redisson
redisson.server:  redis://127.0.0.1:6379

# Cookies time

skillbox.app.jwtExpirationMin: 1440

#Mail service auth properties
skillbox.app.mail.user: aineyltd
skillbox.app.mail.password: jsnmprsudhednkuk

skillbox.app.logRootPath: /app/logs
skillbox.app.cronUploadLogFiles: 11 11 1 * * ?
skillbox.app.cronDeleteLogFolderInRemoteStorage: 44 44 4 */7 * ?

#Dropbox auth
skillbox.app.mail.db.appId: 272m6nu2hx6xsuw
skillbox.app.mail.db.appSecret: ch18f6015h71dqy
skillbox.app.mail.db.refreshToken: ItKarjfZZ-0AAAAAAAAAAR3LEC2hdMoeV7pz3GzICu429lzZrw944fpR_XHhtv0z